version: 2.1


jobs:
  test:
    docker:
      - image: cimg/base:2022.11
    parallelism: 4
    steps:
      - run: lscpu
      - run: ls -all

workflows:
  version: 2
  Build1:
     jobs:
       - test
