version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.09
    resource_class: xlarge
    steps:
      - run: lscpu
    parallelism: 4

workflows:
  version: 2
  Build1:
     jobs:
       - my-job
